"""add photo

Revision ID: 08fcec18af7e
Revises: a22771a62065
Create Date: 2016-12-03 23:50:48.923300

"""

# revision identifiers, used by Alembic.
revision = '08fcec18af7e'
down_revision = 'a22771a62065'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('links')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('links',
    sa.Column('link_id', sa.INTEGER(), nullable=True),
    sa.Column('linked_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['link_id'], ['recipes.id'], ),
    sa.ForeignKeyConstraint(['linked_id'], ['recipes.id'], )
    )
    ### end Alembic commands ###
