"""revise log

Revision ID: 19a5feaa25ab
Revises: eb9e6b53d2ac
Create Date: 2016-12-07 12:58:00.348317

"""

# revision identifiers, used by Alembic.
revision = '19a5feaa25ab'
down_revision = 'eb9e6b53d2ac'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('log_counts')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('log_counts',
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('recipe_id', sa.INTEGER(), nullable=False),
    sa.Column('count', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'recipe_id')
    )
    ### end Alembic commands ###
