"""add fake

Revision ID: 7daf43453aab
Revises: 8a0ef1134c62
Create Date: 2016-12-05 10:53:38.372855

"""

# revision identifiers, used by Alembic.
revision = '7daf43453aab'
down_revision = '8a0ef1134c62'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
