"""add group event report model

Revision ID: 8a0ef1134c62
Revises: None
Create Date: 2016-12-05 10:30:54.257833

"""

# revision identifiers, used by Alembic.
revision = '8a0ef1134c62'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
