"""add group

Revision ID: a22771a62065
Revises: c707ec1c1980
Create Date: 2016-12-01 12:52:09.513567

"""

# revision identifiers, used by Alembic.
revision = 'a22771a62065'
down_revision = 'c707ec1c1980'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('group_member')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('group_member',
    sa.Column('user.id', sa.INTEGER(), nullable=True),
    sa.Column('group_id', sa.INTEGER(), nullable=True),
    sa.Column('member_since', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.ForeignKeyConstraint(['user.id'], ['users.id'], )
    )
    ### end Alembic commands ###
