"""almost done

Revision ID: c398a3589c51
Revises: 7daf43453aab
Create Date: 2016-12-06 13:55:50.643501

"""

# revision identifiers, used by Alembic.
revision = 'c398a3589c51'
down_revision = '7daf43453aab'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
