"""add shell

Revision ID: dd27c179cff7
Revises: 43be1a5c7beb
Create Date: 2016-11-29 21:35:58.178979

"""

# revision identifiers, used by Alembic.
revision = 'dd27c179cff7'
down_revision = '43be1a5c7beb'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
