"""dec06

Revision ID: eb9e6b53d2ac
Revises: c398a3589c51
Create Date: 2016-12-06 16:08:24.092010

"""

# revision identifiers, used by Alembic.
revision = 'eb9e6b53d2ac'
down_revision = 'c398a3589c51'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
