"""last update

Revision ID: fdb71bb9267b
Revises: 19a5feaa25ab
Create Date: 2016-12-08 15:30:02.917805

"""

# revision identifiers, used by Alembic.
revision = 'fdb71bb9267b'
down_revision = '19a5feaa25ab'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
